This is a port of the PR changes found here:
grafana/xk6-grpc pull request #25
Opened 2023-07-08 22:54 UTC by chrismoran-mica

https://github.com/grafana/k6/pull/3159

Let me know if anything else is needed to facilitate this change.

2023-07-08 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-grpc?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-grpc?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-grpc?pullRequest=25) it.</sub>

2023-07-13 07:40 UTC, olegbespalov commented
Hey @chrismoran-mica !

Let's take the latest changes from the https://github.com/grafana/k6/pull/3159, and we can merge it :+1: 

Thanks for your contribution! :bow:

2023-07-13 07:41 UTC, olegbespalov requested changes
Hey @chrismoran-mica !

Let's take the latest changes from the https://github.com/grafana/k6/pull/3159, and we can merge it :+1: 

Thanks for your contribution! :bow:

2023-07-14 17:17 UTC, chrismoran-mica commented
I’m on the road but I’ll get this sorted sometime this weekend. On Jul 13, 2023, at 3:41 AM, Oleg Bespalov ***@***.***> wrote:﻿
@olegbespalov requested changes on this pull request.

Hey @chrismoran-mica !
Let's take the latest changes from the grafana/k6#3159, and we can merge it 👍
Thanks for your contribution! 🙇

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-17 07:33 UTC, olegbespalov approved these changes
Thanks a lot! :bow:

2023-07-17 09:03 UTC, merged